### ISSUE TITLE
[ERROR] Could not resolve "./tailwind.css"

### ISSUE THREAD

**Issue by hirwablessing** [veritem/upro-remix#3]
**Describe the bug**
Can't resolve the path to tailwind css file
**To Reproduce**
run `yarn dev` or `yarn start`

**Expected behavior**
Compile tailwind and start the app successfully without any error
**Screenshots**
![image](https://user-images.githubusercontent.com/50826640/155080664-ef69b8f2-b63b-4493-ba47-c5c2bb5247c9.png)

**Comment by veritem** [comment]
This happens when you first run the app :) 

That file is generated by tailwind itself
